#' @import ncdf4
#' @import reshape2
#' @importFrom ncdf4 nc_open ncvar_get
#' @import data.table
#' @importFrom data.table melt setDT
#' @importFrom stats na.omit
NULL
#' Export grid information to a \code{data.table} from the \code{.nc} file generated by EE.
#' @param filename Character. The name of the \code{.nc} file generated by EE
#' @param ... Characters. The names of the \code{.nc} files generated by EE (maximum 2 at once).
#' @param var_name Character. The name of the variable to read.
#' @param wet_depth Numeric. The minimum depth of the wet cell.
#' @param remove_dry Logical. Should the dry cell be removed?
#' @param verbose Logical. Should print the processing message?
#' @param with_coord Logical. Should the data merge with the coordinates (for plot)?
#' @param nc NetCDF file connection generated by \code{\link[ncdf4]{nc_open}}.
#' @param simplify Logical. If \code{TRUE}, delete unused columns. 
#' @return A \code{data.table} contains grid coordinates and elevation.
#' @export
get_efdc_nc_dt <- function(..., var_name, wet_depth = 0.15, with_coord = T, remove_dry = T, verbose = T){
  fnames_ <- c(...)
  if (length(fnames_) > 2){
    stop('You can only process 2 files at once')
  }
  if (length(fnames_) == 1){
    get_efdc_nc_var(fnames_[1], var_name = var_name, wet_depth = wet_depth, with_coord = with_coord, remove_dry = remove_dry, verbose = verbose)
  } else {
    get_efdc_nc_var(fnames_[1], fnames_[2], var_name = var_name, wet_depth = wet_depth, with_coord = with_coord, remove_dry = remove_dry, verbose = verbose)
  }
}
NULL
#' List the variable names in the NetCDF file.
#' @rdname get_efdc_nc_dt
#' @export
has_variable <- function(filename){
  nc <- nc_open(filename)
  cat(paste("The file has",nc$nvars,"variables: "), names(nc$var))
}

NULL 
#' Read data from EE generated NetCDF files.
#' @rdname get_efdc_nc_dt
#' @export
get_efdc_nc_var <- function(..., var_name, wet_depth = 0.15, verbose = T,  with_coord = T, remove_dry = T){
  fnames_ <- c(...)
  if (length(fnames_) > 2){
    stop('You can only process 2 files at once')
  }
  nc <- nc_open(fnames_[1])
  if (with_coord){
    coord_df <- efdcr::get_efdc_nc_coordinates(nc, simplify = T)
  }
  # add ZBOT 
  if (verbose) {
    cat('Reading bottom elevation (ZBOT)...\n')
  }
  zbot_df <- ncvar_get(nc, 'ZBOT')
  zbot_df_melt <- setDT(reshape2::melt(zbot_df, value.name = 'ZBOT', na.rm = T))
  if (verbose) {
    cat('Finish reading bottom elevation (ZBOT)!\n')
  }
  # return ZBOT
  if (var_name == 'ZBOT'){
    if (with_coord){
      base_df <- merge(coord_df, zbot_df_melt, by = c('Var1', 'Var2'), all.y = T)
      setDT(base_df)
      return(base_df)
    } else {
      return(zbot_df_melt)
    }
  }
  # add WSEL to see if the cell is wet or not
  if (verbose) {
    cat('Reading water surface elevation (WSEL)...\n')
  }
  if (length(fnames_) == 1){
    wsel_df <- ncvar_get(nc, 'WSEL')
    wsel_df_melt <- setDT(reshape2::melt(wsel_df, value.name = 'WSEL'))
    colnames(wsel_df_melt) <- c('Var1', 'Var2', 'Day', 'WSEL')
    var_df <- merge(zbot_df_melt, wsel_df_melt, by.x = c('Var1', 'Var2'), by.y = c('Var1', 'Var2'), all.x = T)
    var_df[, WETFLAG := ifelse((WSEL - ZBOT) > wet_depth | !is.na(WSEL), 1, NA)]
    if (verbose) {
      cat('Finish reading water surface elevation (WSEL)\n')
    }
    if (var_name == 'WSEL') {
      if (remove_dry){
        var_df <- na.omit(var_df, cols = 'WETFLAG')
      }
      if (with_coord){
        base_df <- merge(coord_df, var_df, by = c('Var1', 'Var2'), all.x = T, allow.cartesian = T)
        setDT(base_df)
        return(base_df)
      } else {
        return(var_df)
      }
    }
    # read other data
    if (verbose) {
      cat('Reading variables ', var_name, ' ...\n', sep = '')
    }
    var_df_ <- ncvar_get(nc, var_name)
    var_df_melt_ <- setDT(reshape2::melt(var_df_, value.name = var_name))
    colnames(var_df_melt_) <- c('Var1', 'Var2', 'Day', var_name)
    var_df <- merge(var_df, var_df_melt_, by = c('Var1', 'Var2', 'Day'), all.x = T)
    if (remove_dry){
      var_df <- na.omit(var_df, cols = 'WETFLAG')
    }
    if (with_coord){
      base_df <- merge(coord_df, var_df, by = c('Var1', 'Var2'), allow.cartesian = T)
      setDT(base_df)
      return(base_df)
    } else {
      return(var_df)
    }
  } else { # comapre 2 files
    wsel_df1 <- ncvar_get(nc_open(fnames_[1]), 'WSEL')
    wsel_df2 <- ncvar_get(nc_open(fnames_[2]), 'WSEL')
    wsel_df1_melt <- setDT(reshape2::melt(wsel_df1, value.name = 'WSEL'))
    wsel_df2_melt <- setDT(reshape2::melt(wsel_df2, value.name = 'WSEL'))
    colnames(wsel_df1_melt) <- c('Var1', 'Var2', 'Day', 'WSEL1')
    colnames(wsel_df2_melt) <- c('Var1', 'Var2', 'Day', 'WSEL2')
    var_df <- merge(zbot_df_melt, wsel_df1_melt, by = c('Var1', 'Var2'), all.x = T)
    var_df <- merge(var_df, wsel_df2_melt, by = c('Var1', 'Var2', 'Day'), all.x = T)
    if (verbose) {
      cat('Finish reading water surface elevation (WSEL)\n', 'Comparing Models...\n', sep = '')
    }
    var_df_ <- ncvar_get(nc_open(fnames_[2]), var_name) - ncvar_get(nc_open(fnames_[1]), var_name)
    var_df_melt_ <- setDT(reshape2::melt(var_df_, value.name = 'DIFF'))
    colnames(var_df_melt_) <- c('Var1', 'Var2', 'Day', 'M2-M1')
    var_df1_ <- ncvar_get(nc_open(fnames_[1]), var_name)
    var_df2_ <- ncvar_get(nc_open(fnames_[2]), var_name)
    var_df1_melt_ <- setDT(reshape2::melt(var_df1_, value.name = 'V1'))
    var_df2_melt_ <- setDT(reshape2::melt(var_df2_, value.name = 'V2'))
    colnames(var_df1_melt_) <- c('Var1', 'Var2', 'Day', 'V1')
    colnames(var_df2_melt_) <- c('Var1', 'Var2', 'Day', 'V2')
    var_df <- merge(var_df, var_df1_melt_, by = c('Var1', 'Var2', 'Day'))
    var_df <- merge(var_df, var_df2_melt_, by = c('Var1', 'Var2', 'Day'))
    var_df <- merge(var_df, var_df_melt_, by = c('Var1', 'Var2', 'Day'))
    if (verbose) {
      cat('Finish!\n')
    }
    if (with_coord){
      base_df <- merge(coord_df, var_df, by = c('Var1', 'Var2'), all.x = T, allow.cartesian = T)
      setDT(base_df)
      return(base_df)
    } else {
      return(var_df)
    }
  }
  base_df <- na.omit(base_df, cols = 'WETFLAG')
  if (verbose) {
    cat('Finish!\n')
  }
  return(base_df)
}


NULL
#' Read coordinates from EE generated NetCDF files.
#' @rdname get_efdc_nc_dt
#' @export
get_efdc_nc_coordinates <- function(nc, simplify = T){
  # cat(paste("The file has",nc$nvars,"variables: "), names(nc$var))
  # stop if provided a unused var_name
  # stopifnot(var_name %in% names(nc$var))
  # read grids:
  # longitude at grid center
  lon <- ncvar_get(nc, 'lon')
  # latitude at grid center
  lat <- ncvar_get(nc, 'lat')
  # longitudes of 4 corners of the grid
  lon_bnds <- ncvar_get(nc, 'lon_bnds')
  # longitudes of 4 corners of the grid
  lat_bnds <- ncvar_get(nc, 'lat_bnds')
  lon_melt <- setDT(reshape2::melt(lon))
  lat_melt <- setDT(reshape2::melt(lat))
  lon_bnds_melt <- setDT(reshape2::melt(lon_bnds, value.name = 'lon'))
  lat_bnds_melt <- setDT(reshape2::melt(lat_bnds, value.name = 'lat'))
  lon_lat_df <- merge(lon_bnds_melt, lat_bnds_melt, by = c('Var2', 'Var3', 'Var1'))
  setDT(lon_lat_df)
  lon_lat_df <- na.omit(lon_lat_df)
  n_grids <- sum(!is.na(lon))
  lon_lat_df[, id := rep(1:n_grids, each = 4)]
  # merge center corrdinates:
  lon_melt <- setDT(reshape2::melt(lon, value.name = 'clon'))
  lat_melt <- setDT(reshape2::melt(lat, value.name = 'clat'))
  base_df <- merge(lon_lat_df, lon_melt, by.x = c('Var2', 'Var3'), by.y = c('Var1', 'Var2'))
  base_df <- merge(base_df, lat_melt, by.x = c('Var2', 'Var3'), by.y = c('Var1', 'Var2'))
  if (simplify){
    base_df[, ':='(Var1 = NULL, 
                   clon = NULL, 
                   clat = NULL)]
    colnames(base_df) <- c('Var1', 'Var2', 'lon', 'lat', 'id')
  }
  invisible(base_df)
}

